#!/usr/bin/env bash

# User to log into the remote server.
user=""

# Host of the remote server.
hostname=""

# Root folder of the project to be deployed.
project_root=""

# Default git branch of the project.
default_branch=""

if [[ -z $user ]]; then
    echo "user not set in deployment configuration."
    exit 1
fi

if [[ -z $hostname ]]; then
    echo "hostname not set in deployment configuration."
    exit 1
fi

if [[ -z $project_root ]]; then
    echo "project root not set in deployment configuration."
    exit 1
fi

if [[ -z "$1" ]]; then
    branch=$default_branch
else
    branch=$1
fi

ssh $user@$hostname -t -A  "
cd ${project_root} && ./deploy ${branch}"
