#!/usr/bin/env bash

# User with access to the remote server.
remote_user=""

# Host of the remote server.
remote_host=""

# Root folder of the project to be deployed.
project_root=""

# Default git branch of the project.
git_default_branch="develop"

if [[ -z $remote_user ]]; then
    echo "remote_user not set in deployment configuration."
    exit 1
fi

if [[ -z $remote_host ]]; then
    echo "remote_host not set in deployment configuration."
    exit 1
fi

if [[ -z $project_root ]]; then
    echo "project root not set in deployment configuration."
    exit 1
fi

if [[ -z "$1" ]]; then
    branch=$git_default_branch
else
    branch=$1
fi

ssh $remote_user@$remote_host -t -A  "
cd ${project_root} && ./deploy ${branch}"
